db:
  parent_dir: "db"
  duck:
    dir: "duck_db"
    file: "biocosmos.duckdb"
  lance:
    dir: "lance_db"
    file: "biocosmos.lance"
images:
  # dir: "../../../python/biocosmos-exploration/data/images"
  dir: "/data/data/images/standardized/2024_nymphalidae/nymphalidae_whole_specimen-v250613/"
  table: "nymphalidae"
  # Limit number of images to ingest into the database, set to null for no
  limit: null
gbif:
  dir: "~/Codes/"
  # dir: "../../"
  # dir: "../../../python/biocosmos-exploration/data/lep-meta"
  file: "gbif-lepi-2024-occurrence.tsv"
  table: "gbif_meta"
leptrait:
  # Directory for LepTrait data
  url: "https://raw.githubusercontent.com/hhandika/LepTraits/refs/heads/main/consensus/consensus.csv"
  table: "lep_traits_consensus"
embedder:
  # Skip embedding process if set to true
  skip: true
  # Options: "default", "cpu", "cuda", "mps"
  # "default" will detect the best available accelerator
  device: "cuda"
  # Select GPU for CUDA device, if multiple GPUs are available
  cuda_device: 0
  # Number of samples to process in each batch
  batch_size: 20
  # Reset the inserted images, set to true to re-insert all images
  reset: true
