db:
  duck:
    file: "biocosmos.duckdb"
  lance:
    file: "biocosmos.lance"
images:
  # Table name for storing image in the database
  table: "nymphalidae"
  # Limit number of images to ingest into the database, set to null for no
  limit: null
gbif:
  file: "gbif-lepi-2024-occurrence.tsv"
  table: "gbif_meta"
leptrait:
  url: "https://raw.githubusercontent.com/hhandika/LepTraits/refs/heads/main/consensus/consensus.csv"
  table: "lep_traits_consensus"
embedder:
  # Skip embedding process if set to true
  skip: true
  # Options: "default", "cpu", "cuda", "mps"
  # "default" will detect the best available accelerator
  device: "default"
  # Select GPU for CUDA device, if multiple GPUs are available
  cuda_device: 0
  # Number of samples to process in each batch. Set according to your GPU memory
  batch_size: 20
  # Reset the inserted images, set to true to re-insert all images
  reset: true
